import { existsSync } from "fs"
import fs from "fs/promises"
import path from "path"
import { isCancel, confirm, text, select } from "@clack/prompts"

const ROOT = path.resolve(new URL("..", import.meta.url).pathname)
const PROTO_FILE = path.join(ROOT, ".prototype.json")
const OUT_TS = path.join(ROOT, "src", "lib", "prototype.ts")

async function run() {
  if (existsSync(PROTO_FILE)) {
    console.log("Setup: .prototype.json already exists — skipping setup.")
    return
  }

  console.log("Welcome — project setup for the prototype (first run).")

  const name = await text({
    message: "What is your prototype called?",
    placeholder: "Secret Squirrel",
    validate: (v) => (v.length === 0 ? "Please enter a name" : true),
  })

  if (isCancel(name)) {
    console.log("Setup cancelled.")
    process.exit(1)
  }

  const needsHeader = await confirm({
    message: "Does your prototype need a header?",
    initialValue: false,
  })

  if (isCancel(needsHeader)) {
    console.log("Setup cancelled.")
    process.exit(1)
  }

  let headerText = ""
  if (needsHeader) {
    const t = await text({
      message: "Header text to show (will appear on prototype pages)",
      placeholder: name || "Prototype",
      validate: (v) => (v.length === 0 ? "Please enter header text" : true),
    })

    if (isCancel(t)) {
      console.log("Setup cancelled.")
      process.exit(1)
    }

    headerText = t
  }

  const payload = {
    name,
    header: {
      enabled: !!needsHeader,
      text: headerText || name,
    },
  }

  await fs.writeFile(PROTO_FILE, JSON.stringify(payload, null, 2), "utf8")
  console.log(`Wrote ${PROTO_FILE}`)

  // Ensure out directory
  await fs.mkdir(path.dirname(OUT_TS), { recursive: true })

  const tsContent = `// This file is generated by scripts/setup.mjs - do not edit by hand
export const PROTOTYPE_NAME = ${JSON.stringify(payload.name)} as const
export const PROTOTYPE_HEADER_ENABLED = ${payload.header.enabled} as const
export const PROTOTYPE_HEADER_TEXT = ${JSON.stringify(payload.header.text)} as const
`

  await fs.writeFile(OUT_TS, tsContent, "utf8")
  console.log(`Wrote ${OUT_TS}`)

  console.log("Setup complete. You can now run `pnpm dev`.")
}

run().catch((err) => {
  console.error(err)
  process.exit(1)
})
